apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      #serviceAccountName: vault
      containers:
      - name: vault
        image: hashicorp/vault:latest
        args:
        - "server"
        - "-dev"
        - "-dev-root-token-id=root"          # ⚠️ only for dev!
        - "-dev-listen-address=0.0.0.0:8200"
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        ports:
        - containerPort: 8200
          name: vault
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
  type: ClusterIP
